"""Drop and recreate InfluencerProfile table

Revision ID: 266c5a240fed
Revises: abda03e218c5
Create Date: 2024-06-19 16:27:09.379480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266c5a240fed'
down_revision = 'abda03e218c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencer_profile', 'followers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('influencer_profile', 'platform',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('influencer_profile', 'niche',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencer_profile', 'niche',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('influencer_profile', 'platform',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('influencer_profile', 'followers',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
