"""Initial migration

Revision ID: 3843d0ef766d
Revises: 9199db185aab
Create Date: 2024-06-19 16:15:09.503362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3843d0ef766d'
down_revision = '9199db185aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('niche', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('influencer_id', 'platform', 'niche')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_profile')
    # ### end Alembic commands ###
