"""Influencer Profile

Revision ID: 608250c9de84
Revises: d8ffb950de19
Create Date: 2024-06-19 16:06:37.108000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608250c9de84'
down_revision = 'd8ffb950de19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('niche', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('influencer_id', 'followers', 'platform', 'niche')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_profile')
    # ### end Alembic commands ###
