"""Influencer Profile

Revision ID: 9199db185aab
Revises: 608250c9de84
Create Date: 2024-06-19 16:11:11.122748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9199db185aab'
down_revision = '608250c9de84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'influencer_profile', ['influencer_id', 'platform', 'niche'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'influencer_profile', type_='unique')
    # ### end Alembic commands ###
