"""Drop and recreate InfluencerProfile table

Revision ID: a6aed14d4af0
Revises: 266c5a240fed
Create Date: 2024-06-19 16:31:02.484600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aed14d4af0'
down_revision = '266c5a240fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
